// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin/common.proto

package admin

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import core "core"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Indicates various states of an Execution - both task and workflow
type ExecutionPhase int32

const (
	ExecutionPhase_UNDEFINED ExecutionPhase = 0
	ExecutionPhase_RUNNING   ExecutionPhase = 1
	ExecutionPhase_SUCCEEDED ExecutionPhase = 2
	ExecutionPhase_FAILED    ExecutionPhase = 3
	ExecutionPhase_TIMED_OUT ExecutionPhase = 4
	ExecutionPhase_ABORTED   ExecutionPhase = 5
	ExecutionPhase_QUEUED    ExecutionPhase = 6
)

var ExecutionPhase_name = map[int32]string{
	0: "UNDEFINED",
	1: "RUNNING",
	2: "SUCCEEDED",
	3: "FAILED",
	4: "TIMED_OUT",
	5: "ABORTED",
	6: "QUEUED",
}
var ExecutionPhase_value = map[string]int32{
	"UNDEFINED": 0,
	"RUNNING":   1,
	"SUCCEEDED": 2,
	"FAILED":    3,
	"TIMED_OUT": 4,
	"ABORTED":   5,
	"QUEUED":    6,
}

func (x ExecutionPhase) String() string {
	return proto.EnumName(ExecutionPhase_name, int32(x))
}
func (ExecutionPhase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_d594d2a2c28cfa72, []int{0}
}

type Notification_Type int32

const (
	Notification_UNDEFINED  Notification_Type = 0
	Notification_EMAIL      Notification_Type = 1
	Notification_PAGER_DUTY Notification_Type = 2
	Notification_SLACK      Notification_Type = 3
)

var Notification_Type_name = map[int32]string{
	0: "UNDEFINED",
	1: "EMAIL",
	2: "PAGER_DUTY",
	3: "SLACK",
}
var Notification_Type_value = map[string]int32{
	"UNDEFINED":  0,
	"EMAIL":      1,
	"PAGER_DUTY": 2,
	"SLACK":      3,
}

func (x Notification_Type) String() string {
	return proto.EnumName(Notification_Type_name, int32(x))
}
func (Notification_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_d594d2a2c28cfa72, []int{3, 0}
}

// Encapsulation of fields that identifies a Flyte resource
type Identifier struct {
	Project              string   `protobuf:"bytes,1,opt,name=project" json:"project,omitempty"`
	Domain               string   `protobuf:"bytes,2,opt,name=domain" json:"domain,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identifier) Reset()         { *m = Identifier{} }
func (m *Identifier) String() string { return proto.CompactTextString(m) }
func (*Identifier) ProtoMessage()    {}
func (*Identifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_d594d2a2c28cfa72, []int{0}
}
func (m *Identifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identifier.Unmarshal(m, b)
}
func (m *Identifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identifier.Marshal(b, m, deterministic)
}
func (dst *Identifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identifier.Merge(dst, src)
}
func (m *Identifier) XXX_Size() int {
	return xxx_messageInfo_Identifier.Size(m)
}
func (m *Identifier) XXX_DiscardUnknown() {
	xxx_messageInfo_Identifier.DiscardUnknown(m)
}

var xxx_messageInfo_Identifier proto.InternalMessageInfo

func (m *Identifier) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Identifier) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Identifier) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type IdentifierList struct {
	Entities             []*Identifier `protobuf:"bytes,1,rep,name=entities" json:"entities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *IdentifierList) Reset()         { *m = IdentifierList{} }
func (m *IdentifierList) String() string { return proto.CompactTextString(m) }
func (*IdentifierList) ProtoMessage()    {}
func (*IdentifierList) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_d594d2a2c28cfa72, []int{1}
}
func (m *IdentifierList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentifierList.Unmarshal(m, b)
}
func (m *IdentifierList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentifierList.Marshal(b, m, deterministic)
}
func (dst *IdentifierList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentifierList.Merge(dst, src)
}
func (m *IdentifierList) XXX_Size() int {
	return xxx_messageInfo_IdentifierList.Size(m)
}
func (m *IdentifierList) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentifierList.DiscardUnknown(m)
}

var xxx_messageInfo_IdentifierList proto.InternalMessageInfo

func (m *IdentifierList) GetEntities() []*Identifier {
	if m != nil {
		return m.Entities
	}
	return nil
}

// Declares an input parameter.
type Parameter struct {
	// +required Variable. Defines a name and a type to reference/compare through out the system.
	Var *core.Variable `protobuf:"bytes,1,opt,name=var" json:"var,omitempty"`
	// +optional
	//
	// Types that are valid to be assigned to Default:
	//	*Parameter_Value
	Default isParameter_Default `protobuf_oneof:"default"`
	// +optional, is this value required to be filled.
	Required bool `protobuf:"varint,3,opt,name=required" json:"required,omitempty"`
	// +optional string describing input variable
	Description          string   `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Parameter) Reset()         { *m = Parameter{} }
func (m *Parameter) String() string { return proto.CompactTextString(m) }
func (*Parameter) ProtoMessage()    {}
func (*Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_d594d2a2c28cfa72, []int{2}
}
func (m *Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parameter.Unmarshal(m, b)
}
func (m *Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parameter.Marshal(b, m, deterministic)
}
func (dst *Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parameter.Merge(dst, src)
}
func (m *Parameter) XXX_Size() int {
	return xxx_messageInfo_Parameter.Size(m)
}
func (m *Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_Parameter proto.InternalMessageInfo

type isParameter_Default interface {
	isParameter_Default()
}

type Parameter_Value struct {
	Value *core.Literal `protobuf:"bytes,2,opt,name=value,oneof"`
}

func (*Parameter_Value) isParameter_Default() {}

func (m *Parameter) GetDefault() isParameter_Default {
	if m != nil {
		return m.Default
	}
	return nil
}

func (m *Parameter) GetVar() *core.Variable {
	if m != nil {
		return m.Var
	}
	return nil
}

func (m *Parameter) GetValue() *core.Literal {
	if x, ok := m.GetDefault().(*Parameter_Value); ok {
		return x.Value
	}
	return nil
}

func (m *Parameter) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *Parameter) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Parameter) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Parameter_OneofMarshaler, _Parameter_OneofUnmarshaler, _Parameter_OneofSizer, []interface{}{
		(*Parameter_Value)(nil),
	}
}

func _Parameter_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Parameter)
	// default
	switch x := m.Default.(type) {
	case *Parameter_Value:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Value); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Parameter.Default has unexpected type %T", x)
	}
	return nil
}

func _Parameter_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Parameter)
	switch tag {
	case 2: // default.value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(core.Literal)
		err := b.DecodeMessage(msg)
		m.Default = &Parameter_Value{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Parameter_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Parameter)
	// default
	switch x := m.Default.(type) {
	case *Parameter_Value:
		s := proto.Size(x.Value)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Structure of notifications based on execution status.
type Notification struct {
	Type                 Notification_Type `protobuf:"varint,1,opt,name=type,enum=admin.Notification_Type" json:"type,omitempty"`
	Phases               []ExecutionPhase  `protobuf:"varint,2,rep,packed,name=phases,enum=admin.ExecutionPhase" json:"phases,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_d594d2a2c28cfa72, []int{3}
}
func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (dst *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(dst, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetType() Notification_Type {
	if m != nil {
		return m.Type
	}
	return Notification_UNDEFINED
}

func (m *Notification) GetPhases() []ExecutionPhase {
	if m != nil {
		return m.Phases
	}
	return nil
}

func init() {
	proto.RegisterType((*Identifier)(nil), "admin.Identifier")
	proto.RegisterType((*IdentifierList)(nil), "admin.IdentifierList")
	proto.RegisterType((*Parameter)(nil), "admin.Parameter")
	proto.RegisterType((*Notification)(nil), "admin.Notification")
	proto.RegisterEnum("admin.ExecutionPhase", ExecutionPhase_name, ExecutionPhase_value)
	proto.RegisterEnum("admin.Notification_Type", Notification_Type_name, Notification_Type_value)
}

func init() { proto.RegisterFile("admin/common.proto", fileDescriptor_common_d594d2a2c28cfa72) }

var fileDescriptor_common_d594d2a2c28cfa72 = []byte{
	// 466 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x86, 0x97, 0xa6, 0x9f, 0xa7, 0x2c, 0x0a, 0xe6, 0x43, 0x51, 0xaf, 0xaa, 0x4a, 0x48, 0x15,
	0x62, 0x99, 0x54, 0x2e, 0xb9, 0x40, 0x6d, 0xe3, 0x8d, 0x88, 0x2e, 0x2b, 0x5e, 0x83, 0x04, 0x37,
	0x93, 0x97, 0x9c, 0x0a, 0xa3, 0x26, 0x0e, 0x8e, 0x3b, 0xb1, 0x1f, 0xc3, 0x3d, 0x3f, 0x13, 0xd9,
	0x29, 0xdb, 0xe0, 0x2e, 0xe7, 0x7d, 0x9e, 0x1c, 0xbd, 0x47, 0x32, 0x10, 0x9e, 0x17, 0xa2, 0x3c,
	0xcd, 0x64, 0x51, 0xc8, 0x32, 0xac, 0x94, 0xd4, 0x92, 0x74, 0x6c, 0x36, 0x7a, 0x9e, 0x49, 0x85,
	0xa7, 0xa2, 0xd4, 0xa8, 0xb6, 0x3c, 0xc3, 0x06, 0x8e, 0x9e, 0xd9, 0x74, 0x27, 0x34, 0x2a, 0xbe,
	0xab, 0x9b, 0x70, 0xc2, 0x00, 0xe2, 0x1c, 0x4b, 0x2d, 0xb6, 0x02, 0x15, 0x09, 0xa0, 0x57, 0x29,
	0xf9, 0x1d, 0x33, 0x1d, 0x38, 0x63, 0x67, 0x3a, 0x60, 0x7f, 0x47, 0xf2, 0x12, 0xba, 0xb9, 0x2c,
	0xb8, 0x28, 0x83, 0x96, 0x05, 0x87, 0x89, 0x10, 0x68, 0x97, 0xbc, 0xc0, 0xc0, 0xb5, 0xa9, 0xfd,
	0x9e, 0xbc, 0x07, 0xef, 0x61, 0xe7, 0x4a, 0xd4, 0x9a, 0x9c, 0x40, 0xdf, 0xcc, 0x5a, 0x60, 0x1d,
	0x38, 0x63, 0x77, 0x3a, 0x9c, 0x3d, 0x0d, 0x6d, 0xd5, 0xf0, 0x41, 0x64, 0xf7, 0xca, 0xe4, 0x97,
	0x03, 0x83, 0x35, 0x57, 0xbc, 0x40, 0x8d, 0x8a, 0x8c, 0xc1, 0xbd, 0xe5, 0xca, 0x16, 0x1a, 0xce,
	0xbc, 0xd0, 0x5c, 0x11, 0x7e, 0xe6, 0x4a, 0xf0, 0x9b, 0x1d, 0x32, 0x83, 0xc8, 0x2b, 0xe8, 0xdc,
	0xf2, 0xdd, 0x1e, 0x6d, 0xb7, 0xe1, 0xec, 0xb8, 0x71, 0x56, 0xcd, 0xa5, 0x1f, 0x8e, 0x58, 0x43,
	0xc9, 0x08, 0xfa, 0x0a, 0x7f, 0xec, 0x85, 0xc2, 0xdc, 0xf6, 0xed, 0xb3, 0xfb, 0x99, 0x8c, 0x61,
	0x98, 0x63, 0x9d, 0x29, 0x51, 0x69, 0x21, 0xcb, 0xa0, 0x6d, 0xcf, 0x79, 0x1c, 0x2d, 0x06, 0xd0,
	0xcb, 0x71, 0xcb, 0xf7, 0x3b, 0x3d, 0xf9, 0xed, 0xc0, 0x93, 0x44, 0x9a, 0xda, 0x19, 0x37, 0x8c,
	0xbc, 0x81, 0xb6, 0xbe, 0xab, 0xd0, 0x76, 0xf4, 0x66, 0xc1, 0xe1, 0xb6, 0xc7, 0x4a, 0xb8, 0xb9,
	0xab, 0x90, 0x59, 0x8b, 0x9c, 0x40, 0xb7, 0xfa, 0xc6, 0x6b, 0xac, 0x83, 0xd6, 0xd8, 0x9d, 0x7a,
	0xb3, 0x17, 0x07, 0x9f, 0xfe, 0xc4, 0x6c, 0x6f, 0xe4, 0xb5, 0xa1, 0xec, 0x20, 0x4d, 0xde, 0x41,
	0xdb, 0xfc, 0x4c, 0x8e, 0x61, 0x90, 0x26, 0x11, 0x3d, 0x8b, 0x13, 0x1a, 0xf9, 0x47, 0x64, 0x00,
	0x1d, 0x7a, 0x31, 0x8f, 0x57, 0xbe, 0x43, 0x3c, 0x80, 0xf5, 0xfc, 0x9c, 0xb2, 0xeb, 0x28, 0xdd,
	0x7c, 0xf1, 0x5b, 0x06, 0x5d, 0xad, 0xe6, 0xcb, 0x8f, 0xbe, 0xfb, 0x5a, 0x82, 0xf7, 0xef, 0xda,
	0xff, 0xd7, 0x0c, 0xa1, 0xc7, 0xd2, 0x24, 0x89, 0x93, 0x73, 0xdf, 0x31, 0xec, 0x2a, 0x5d, 0x2e,
	0x29, 0x8d, 0x68, 0xe4, 0xb7, 0x08, 0x40, 0xf7, 0x6c, 0x1e, 0xaf, 0x68, 0xe4, 0xbb, 0x06, 0x6d,
	0xe2, 0x0b, 0x1a, 0x5d, 0x5f, 0xa6, 0x1b, 0xbf, 0x6d, 0x7e, 0x9b, 0x2f, 0x2e, 0xd9, 0x86, 0x46,
	0x7e, 0xc7, 0x78, 0x9f, 0x52, 0x9a, 0xd2, 0xc8, 0xef, 0x2e, 0x7a, 0x5f, 0x9b, 0x47, 0x78, 0xd3,
	0xb5, 0x0f, 0xec, 0xed, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0e, 0xa7, 0x10, 0x81, 0xa8, 0x02,
	0x00, 0x00,
}
