// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin/execution.proto

package admin

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import core "core"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ExecutionMetadata_ExecutionMode int32

const (
	ExecutionMetadata_MANUAL    ExecutionMetadata_ExecutionMode = 0
	ExecutionMetadata_SCHEDULED ExecutionMetadata_ExecutionMode = 1
	ExecutionMetadata_SYSTEM    ExecutionMetadata_ExecutionMode = 2
)

var ExecutionMetadata_ExecutionMode_name = map[int32]string{
	0: "MANUAL",
	1: "SCHEDULED",
	2: "SYSTEM",
}
var ExecutionMetadata_ExecutionMode_value = map[string]int32{
	"MANUAL":    0,
	"SCHEDULED": 1,
	"SYSTEM":    2,
}

func (x ExecutionMetadata_ExecutionMode) String() string {
	return proto.EnumName(ExecutionMetadata_ExecutionMode_name, int32(x))
}
func (ExecutionMetadata_ExecutionMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_execution_2c3ae5aaddaa6b9e, []int{6, 0}
}

type ExecutionCreateRequest struct {
	Id                   *Identifier    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Spec                 *ExecutionSpec `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ExecutionCreateRequest) Reset()         { *m = ExecutionCreateRequest{} }
func (m *ExecutionCreateRequest) String() string { return proto.CompactTextString(m) }
func (*ExecutionCreateRequest) ProtoMessage()    {}
func (*ExecutionCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_execution_2c3ae5aaddaa6b9e, []int{0}
}
func (m *ExecutionCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutionCreateRequest.Unmarshal(m, b)
}
func (m *ExecutionCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutionCreateRequest.Marshal(b, m, deterministic)
}
func (dst *ExecutionCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionCreateRequest.Merge(dst, src)
}
func (m *ExecutionCreateRequest) XXX_Size() int {
	return xxx_messageInfo_ExecutionCreateRequest.Size(m)
}
func (m *ExecutionCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionCreateRequest proto.InternalMessageInfo

func (m *ExecutionCreateRequest) GetId() *Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ExecutionCreateRequest) GetSpec() *ExecutionSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type ExecutionCreateResult struct {
	Urn                  string   `protobuf:"bytes,1,opt,name=urn" json:"urn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecutionCreateResult) Reset()         { *m = ExecutionCreateResult{} }
func (m *ExecutionCreateResult) String() string { return proto.CompactTextString(m) }
func (*ExecutionCreateResult) ProtoMessage()    {}
func (*ExecutionCreateResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_execution_2c3ae5aaddaa6b9e, []int{1}
}
func (m *ExecutionCreateResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutionCreateResult.Unmarshal(m, b)
}
func (m *ExecutionCreateResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutionCreateResult.Marshal(b, m, deterministic)
}
func (dst *ExecutionCreateResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionCreateResult.Merge(dst, src)
}
func (m *ExecutionCreateResult) XXX_Size() int {
	return xxx_messageInfo_ExecutionCreateResult.Size(m)
}
func (m *ExecutionCreateResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionCreateResult.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionCreateResult proto.InternalMessageInfo

func (m *ExecutionCreateResult) GetUrn() string {
	if m != nil {
		return m.Urn
	}
	return ""
}

type Execution struct {
	Id                   *Identifier      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Urn                  string           `protobuf:"bytes,2,opt,name=urn" json:"urn,omitempty"`
	Status               *ExecutionStatus `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
	Spec                 *ExecutionSpec   `protobuf:"bytes,4,opt,name=spec" json:"spec,omitempty"`
	Result               *ExecutionResult `protobuf:"bytes,5,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Execution) Reset()         { *m = Execution{} }
func (m *Execution) String() string { return proto.CompactTextString(m) }
func (*Execution) ProtoMessage()    {}
func (*Execution) Descriptor() ([]byte, []int) {
	return fileDescriptor_execution_2c3ae5aaddaa6b9e, []int{2}
}
func (m *Execution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Execution.Unmarshal(m, b)
}
func (m *Execution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Execution.Marshal(b, m, deterministic)
}
func (dst *Execution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Execution.Merge(dst, src)
}
func (m *Execution) XXX_Size() int {
	return xxx_messageInfo_Execution.Size(m)
}
func (m *Execution) XXX_DiscardUnknown() {
	xxx_messageInfo_Execution.DiscardUnknown(m)
}

var xxx_messageInfo_Execution proto.InternalMessageInfo

func (m *Execution) GetId() *Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Execution) GetUrn() string {
	if m != nil {
		return m.Urn
	}
	return ""
}

func (m *Execution) GetStatus() *ExecutionStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Execution) GetSpec() *ExecutionSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Execution) GetResult() *ExecutionResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type ExecutionList struct {
	Executions           []*Execution `protobuf:"bytes,1,rep,name=executions" json:"executions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ExecutionList) Reset()         { *m = ExecutionList{} }
func (m *ExecutionList) String() string { return proto.CompactTextString(m) }
func (*ExecutionList) ProtoMessage()    {}
func (*ExecutionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_execution_2c3ae5aaddaa6b9e, []int{3}
}
func (m *ExecutionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutionList.Unmarshal(m, b)
}
func (m *ExecutionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutionList.Marshal(b, m, deterministic)
}
func (dst *ExecutionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionList.Merge(dst, src)
}
func (m *ExecutionList) XXX_Size() int {
	return xxx_messageInfo_ExecutionList.Size(m)
}
func (m *ExecutionList) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionList.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionList proto.InternalMessageInfo

func (m *ExecutionList) GetExecutions() []*Execution {
	if m != nil {
		return m.Executions
	}
	return nil
}

type ExecutionStatus struct {
	// Phase of the executions
	Phase                ExecutionPhase `protobuf:"varint,1,opt,name=phase,enum=admin.ExecutionPhase" json:"phase,omitempty"`
	WorkflowUrn          string         `protobuf:"bytes,2,opt,name=workflow_urn,json=workflowUrn" json:"workflow_urn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ExecutionStatus) Reset()         { *m = ExecutionStatus{} }
func (m *ExecutionStatus) String() string { return proto.CompactTextString(m) }
func (*ExecutionStatus) ProtoMessage()    {}
func (*ExecutionStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_execution_2c3ae5aaddaa6b9e, []int{4}
}
func (m *ExecutionStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutionStatus.Unmarshal(m, b)
}
func (m *ExecutionStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutionStatus.Marshal(b, m, deterministic)
}
func (dst *ExecutionStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionStatus.Merge(dst, src)
}
func (m *ExecutionStatus) XXX_Size() int {
	return xxx_messageInfo_ExecutionStatus.Size(m)
}
func (m *ExecutionStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionStatus proto.InternalMessageInfo

func (m *ExecutionStatus) GetPhase() ExecutionPhase {
	if m != nil {
		return m.Phase
	}
	return ExecutionPhase_UNDEFINED
}

func (m *ExecutionStatus) GetWorkflowUrn() string {
	if m != nil {
		return m.WorkflowUrn
	}
	return ""
}

// Encapsultes the results of the Execution
type ExecutionResult struct {
	// Types that are valid to be assigned to OutputResult:
	//	*ExecutionResult_Outputs
	//	*ExecutionResult_Error
	OutputResult         isExecutionResult_OutputResult `protobuf_oneof:"output_result"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ExecutionResult) Reset()         { *m = ExecutionResult{} }
func (m *ExecutionResult) String() string { return proto.CompactTextString(m) }
func (*ExecutionResult) ProtoMessage()    {}
func (*ExecutionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_execution_2c3ae5aaddaa6b9e, []int{5}
}
func (m *ExecutionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutionResult.Unmarshal(m, b)
}
func (m *ExecutionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutionResult.Marshal(b, m, deterministic)
}
func (dst *ExecutionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionResult.Merge(dst, src)
}
func (m *ExecutionResult) XXX_Size() int {
	return xxx_messageInfo_ExecutionResult.Size(m)
}
func (m *ExecutionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionResult.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionResult proto.InternalMessageInfo

type isExecutionResult_OutputResult interface {
	isExecutionResult_OutputResult()
}

type ExecutionResult_Outputs struct {
	Outputs *core.NamedValueCollection `protobuf:"bytes,1,opt,name=outputs,oneof"`
}
type ExecutionResult_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,oneof"`
}

func (*ExecutionResult_Outputs) isExecutionResult_OutputResult() {}
func (*ExecutionResult_Error) isExecutionResult_OutputResult()   {}

func (m *ExecutionResult) GetOutputResult() isExecutionResult_OutputResult {
	if m != nil {
		return m.OutputResult
	}
	return nil
}

func (m *ExecutionResult) GetOutputs() *core.NamedValueCollection {
	if x, ok := m.GetOutputResult().(*ExecutionResult_Outputs); ok {
		return x.Outputs
	}
	return nil
}

func (m *ExecutionResult) GetError() *Error {
	if x, ok := m.GetOutputResult().(*ExecutionResult_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ExecutionResult) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ExecutionResult_OneofMarshaler, _ExecutionResult_OneofUnmarshaler, _ExecutionResult_OneofSizer, []interface{}{
		(*ExecutionResult_Outputs)(nil),
		(*ExecutionResult_Error)(nil),
	}
}

func _ExecutionResult_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ExecutionResult)
	// output_result
	switch x := m.OutputResult.(type) {
	case *ExecutionResult_Outputs:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Outputs); err != nil {
			return err
		}
	case *ExecutionResult_Error:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ExecutionResult.OutputResult has unexpected type %T", x)
	}
	return nil
}

func _ExecutionResult_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ExecutionResult)
	switch tag {
	case 1: // output_result.outputs
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(core.NamedValueCollection)
		err := b.DecodeMessage(msg)
		m.OutputResult = &ExecutionResult_Outputs{msg}
		return true, err
	case 2: // output_result.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Error)
		err := b.DecodeMessage(msg)
		m.OutputResult = &ExecutionResult_Error{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ExecutionResult_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ExecutionResult)
	// output_result
	switch x := m.OutputResult.(type) {
	case *ExecutionResult_Outputs:
		s := proto.Size(x.Outputs)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ExecutionResult_Error:
		s := proto.Size(x.Error)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ExecutionMetadata struct {
	Mode ExecutionMetadata_ExecutionMode `protobuf:"varint,1,opt,name=mode,enum=admin.ExecutionMetadata_ExecutionMode" json:"mode,omitempty"`
	// Identifier of the entity that triggered this execution.
	Principal string `protobuf:"bytes,2,opt,name=principal" json:"principal,omitempty"`
	// Indicates the "nestedness" of this execution.
	// If a user launches a workflow execution, the default nesting is 0.
	// If this execution further launches a workflow (child workflow), the nesting level is incremented by 0 => 1
	// Generally, if workflow at nesting level k launches a workflow then the child workflow will have
	// nesting = k + 1.
	Nesting              int32    `protobuf:"varint,3,opt,name=nesting" json:"nesting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecutionMetadata) Reset()         { *m = ExecutionMetadata{} }
func (m *ExecutionMetadata) String() string { return proto.CompactTextString(m) }
func (*ExecutionMetadata) ProtoMessage()    {}
func (*ExecutionMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_execution_2c3ae5aaddaa6b9e, []int{6}
}
func (m *ExecutionMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutionMetadata.Unmarshal(m, b)
}
func (m *ExecutionMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutionMetadata.Marshal(b, m, deterministic)
}
func (dst *ExecutionMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionMetadata.Merge(dst, src)
}
func (m *ExecutionMetadata) XXX_Size() int {
	return xxx_messageInfo_ExecutionMetadata.Size(m)
}
func (m *ExecutionMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionMetadata proto.InternalMessageInfo

func (m *ExecutionMetadata) GetMode() ExecutionMetadata_ExecutionMode {
	if m != nil {
		return m.Mode
	}
	return ExecutionMetadata_MANUAL
}

func (m *ExecutionMetadata) GetPrincipal() string {
	if m != nil {
		return m.Principal
	}
	return ""
}

func (m *ExecutionMetadata) GetNesting() int32 {
	if m != nil {
		return m.Nesting
	}
	return 0
}

type ExecutionSpec struct {
	// Launch plan urn to be executed
	LaunchPlanUrn string `protobuf:"bytes,1,opt,name=launch_plan_urn,json=launchPlanUrn" json:"launch_plan_urn,omitempty"`
	// Input values to be passed for the execution
	Inputs *core.NamedValueCollection `protobuf:"bytes,2,opt,name=inputs" json:"inputs,omitempty"`
	// Metadata for the execution
	Metadata *ExecutionMetadata `protobuf:"bytes,3,opt,name=metadata" json:"metadata,omitempty"`
	// List of notifications based on Execution status transitions
	Notifications        []*Notification `protobuf:"bytes,4,rep,name=notifications" json:"notifications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ExecutionSpec) Reset()         { *m = ExecutionSpec{} }
func (m *ExecutionSpec) String() string { return proto.CompactTextString(m) }
func (*ExecutionSpec) ProtoMessage()    {}
func (*ExecutionSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_execution_2c3ae5aaddaa6b9e, []int{7}
}
func (m *ExecutionSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutionSpec.Unmarshal(m, b)
}
func (m *ExecutionSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutionSpec.Marshal(b, m, deterministic)
}
func (dst *ExecutionSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionSpec.Merge(dst, src)
}
func (m *ExecutionSpec) XXX_Size() int {
	return xxx_messageInfo_ExecutionSpec.Size(m)
}
func (m *ExecutionSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionSpec proto.InternalMessageInfo

func (m *ExecutionSpec) GetLaunchPlanUrn() string {
	if m != nil {
		return m.LaunchPlanUrn
	}
	return ""
}

func (m *ExecutionSpec) GetInputs() *core.NamedValueCollection {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *ExecutionSpec) GetMetadata() *ExecutionMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ExecutionSpec) GetNotifications() []*Notification {
	if m != nil {
		return m.Notifications
	}
	return nil
}

func init() {
	proto.RegisterType((*ExecutionCreateRequest)(nil), "admin.ExecutionCreateRequest")
	proto.RegisterType((*ExecutionCreateResult)(nil), "admin.ExecutionCreateResult")
	proto.RegisterType((*Execution)(nil), "admin.Execution")
	proto.RegisterType((*ExecutionList)(nil), "admin.ExecutionList")
	proto.RegisterType((*ExecutionStatus)(nil), "admin.ExecutionStatus")
	proto.RegisterType((*ExecutionResult)(nil), "admin.ExecutionResult")
	proto.RegisterType((*ExecutionMetadata)(nil), "admin.ExecutionMetadata")
	proto.RegisterType((*ExecutionSpec)(nil), "admin.ExecutionSpec")
	proto.RegisterEnum("admin.ExecutionMetadata_ExecutionMode", ExecutionMetadata_ExecutionMode_name, ExecutionMetadata_ExecutionMode_value)
}

func init() { proto.RegisterFile("admin/execution.proto", fileDescriptor_execution_2c3ae5aaddaa6b9e) }

var fileDescriptor_execution_2c3ae5aaddaa6b9e = []byte{
	// 571 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x51, 0x6f, 0xd3, 0x3c,
	0x14, 0x5d, 0xb2, 0xb6, 0xfb, 0x7a, 0xb7, 0x7e, 0x6b, 0xcd, 0x3a, 0x45, 0x15, 0x0f, 0x5b, 0x84,
	0xa6, 0x22, 0xa4, 0x0c, 0x15, 0x34, 0x09, 0xde, 0xba, 0xae, 0x52, 0x91, 0xda, 0x6a, 0x72, 0x29,
	0x12, 0xbc, 0x54, 0x26, 0x71, 0x99, 0x45, 0x62, 0x07, 0xc7, 0xd1, 0x78, 0xe4, 0x9f, 0xf1, 0xce,
	0x6f, 0xe0, 0xc7, 0xa0, 0x38, 0x4e, 0x1a, 0x5a, 0xd0, 0x78, 0x6b, 0xef, 0x3d, 0xe7, 0xf8, 0xde,
	0xe3, 0x13, 0x43, 0x97, 0x04, 0x11, 0xe3, 0x97, 0xf4, 0x2b, 0xf5, 0x53, 0xc5, 0x04, 0xf7, 0x62,
	0x29, 0x94, 0x40, 0x75, 0x5d, 0xee, 0x9d, 0xf8, 0x42, 0xd2, 0x4b, 0xc6, 0x15, 0x95, 0x6b, 0xe2,
	0xd3, 0xbc, 0xd9, 0x43, 0x39, 0xc7, 0x17, 0x51, 0x54, 0x10, 0x7a, 0x1d, 0xa3, 0x23, 0xa5, 0x90,
	0x79, 0xc9, 0xa5, 0x70, 0x3a, 0x2e, 0x64, 0x47, 0x92, 0x12, 0x45, 0x31, 0xfd, 0x92, 0xd2, 0x44,
	0xa1, 0x73, 0xb0, 0x59, 0xe0, 0x58, 0x67, 0x56, 0xff, 0x70, 0xd0, 0xf1, 0x34, 0xd3, 0x7b, 0x13,
	0x50, 0xae, 0xd8, 0x9a, 0x51, 0x89, 0x6d, 0x16, 0xa0, 0x3e, 0xd4, 0x92, 0x98, 0xfa, 0x8e, 0xad,
	0x41, 0x27, 0x06, 0x54, 0xea, 0x2d, 0x62, 0xea, 0x63, 0x8d, 0x70, 0x9f, 0x42, 0x77, 0xe7, 0x98,
	0x24, 0x0d, 0x15, 0x6a, 0xc3, 0x7e, 0x2a, 0xb9, 0x3e, 0xa6, 0x89, 0xb3, 0x9f, 0xee, 0x0f, 0x0b,
	0x9a, 0x25, 0xf6, 0x5f, 0xa6, 0x30, 0x12, 0x76, 0x29, 0x81, 0x3c, 0x68, 0x24, 0x8a, 0xa8, 0x34,
	0x71, 0xf6, 0x35, 0xf1, 0x74, 0x67, 0x32, 0xdd, 0xc5, 0x06, 0x55, 0xee, 0x51, 0x7b, 0x68, 0x8f,
	0x4c, 0x59, 0xea, 0xc1, 0x9d, 0xfa, 0x9f, 0x95, 0xf3, 0xb5, 0xb0, 0x41, 0xb9, 0x43, 0x68, 0x95,
	0xad, 0x29, 0x4b, 0x14, 0x7a, 0x0e, 0x50, 0x5e, 0x63, 0xe2, 0x58, 0x67, 0xfb, 0xfd, 0xc3, 0x41,
	0x7b, 0x47, 0xa4, 0x82, 0x71, 0x09, 0x1c, 0x6f, 0xcd, 0x8d, 0x9e, 0x41, 0x3d, 0xbe, 0x23, 0x09,
	0xd5, 0xbe, 0xfc, 0x3f, 0xe8, 0x6e, 0xf3, 0x6f, 0xb3, 0x26, 0xce, 0x31, 0xe8, 0x1c, 0x8e, 0xee,
	0x85, 0xfc, 0xbc, 0x0e, 0xc5, 0xfd, 0x6a, 0xe3, 0xd3, 0x61, 0x51, 0x5b, 0x4a, 0xee, 0x7e, 0xb3,
	0x2a, 0x67, 0x98, 0x8b, 0xb9, 0x82, 0x03, 0x91, 0xaa, 0x38, 0x55, 0x89, 0x71, 0xbf, 0xe7, 0x65,
	0x39, 0xf3, 0xe6, 0x24, 0xa2, 0xc1, 0x3b, 0x12, 0xa6, 0x74, 0x24, 0xc2, 0x90, 0xfa, 0x19, 0x65,
	0xb2, 0x87, 0x0b, 0x30, 0x7a, 0x02, 0x75, 0x9d, 0x2f, 0x13, 0x8a, 0xa3, 0x62, 0xb6, 0xac, 0x36,
	0xd9, 0xc3, 0x79, 0xf3, 0xfa, 0x18, 0x5a, 0x39, 0x61, 0x65, 0x8c, 0xfa, 0x6e, 0x41, 0xa7, 0x1c,
	0x61, 0x46, 0x15, 0x09, 0x88, 0x22, 0xe8, 0x35, 0xd4, 0x22, 0x11, 0x14, 0x7b, 0x5e, 0x6c, 0xef,
	0x59, 0xe0, 0x2a, 0x15, 0x11, 0x50, 0xac, 0x39, 0xe8, 0x31, 0x34, 0x63, 0xc9, 0xb8, 0xcf, 0x62,
	0x12, 0x9a, 0xa5, 0x37, 0x05, 0xe4, 0xc0, 0x01, 0xa7, 0x89, 0x62, 0xfc, 0x93, 0xce, 0x48, 0x1d,
	0x17, 0x7f, 0xdd, 0xab, 0xca, 0x95, 0x65, 0x72, 0x08, 0xa0, 0x31, 0x1b, 0xce, 0x97, 0xc3, 0x69,
	0x7b, 0x0f, 0xb5, 0xa0, 0xb9, 0x18, 0x4d, 0xc6, 0x37, 0xcb, 0xe9, 0xf8, 0xa6, 0x6d, 0x65, 0xad,
	0xc5, 0xfb, 0xc5, 0xdb, 0xf1, 0xac, 0x6d, 0xbb, 0x3f, 0xad, 0x0a, 0x31, 0x8b, 0x0c, 0xba, 0x80,
	0xe3, 0x90, 0xa4, 0xdc, 0xbf, 0x5b, 0xc5, 0x21, 0xe1, 0xab, 0x4d, 0xce, 0x5b, 0x79, 0xf9, 0x36,
	0x24, 0x7c, 0x29, 0x39, 0x1a, 0x40, 0x83, 0x71, 0xed, 0xb4, 0xfd, 0x90, 0xd3, 0xd8, 0x20, 0xd1,
	0x4b, 0xf8, 0x2f, 0x32, 0xdb, 0x9b, 0x90, 0x3b, 0x7f, 0x73, 0x07, 0x97, 0x48, 0xf4, 0x0a, 0x5a,
	0x5c, 0x64, 0x9f, 0x8e, 0x4f, 0xf2, 0x00, 0xd6, 0x74, 0x00, 0x1f, 0x19, 0xea, 0xbc, 0xd2, 0xc3,
	0xbf, 0x23, 0xaf, 0x0f, 0x3e, 0xe4, 0xcf, 0xcd, 0xc7, 0x86, 0x7e, 0x38, 0x5e, 0xfc, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0xc3, 0x75, 0xff, 0xa6, 0x95, 0x04, 0x00, 0x00,
}
