// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2019-03-20 11:12:04.569788929 -0700 PDT m=+5.040273800

package admin

import (
	"fmt"

	"github.com/spf13/pflag"
)

// GetPFlagSet will return strongly types pflags for all fields in Config and its nested types. The format of the
// flags is json-name.json-sub-name... etc.
func (Config) GetPFlagSet(prefix string) *pflag.FlagSet {
	cmdFlags := pflag.NewFlagSet("Config", pflag.ExitOnError)
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "endpoint"), "", "For admin types,  specify where the uri of the service is located.")
	return cmdFlags
}
