// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

package admin

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
	"testing"

	"github.com/mitchellh/mapstructure"
	"github.com/stretchr/testify/assert"
)

var dereferencableKindsConfig = map[reflect.Kind]struct{}{
	reflect.Array: {}, reflect.Chan: {}, reflect.Map: {}, reflect.Ptr: {}, reflect.Slice: {},
}

// Checks if t is a kind that can be dereferenced to get its underlying type.
func canGetElementConfig(t reflect.Kind) bool {
	_, exists := dereferencableKindsConfig[t]
	return exists
}

// This decoder hook tests types for json unmarshaling capability. If implemented, it uses json unmarshal to build the
// object. Otherwise, it'll just pass on the original data.
func jsonUnmarshalerHookConfig(_, to reflect.Type, data interface{}) (interface{}, error) {
	unmarshalerType := reflect.TypeOf((*json.Unmarshaler)(nil)).Elem()
	if to.Implements(unmarshalerType) || reflect.PtrTo(to).Implements(unmarshalerType) ||
		(canGetElementConfig(to.Kind()) && to.Elem().Implements(unmarshalerType)) {

		raw, err := json.Marshal(data)
		if err != nil {
			fmt.Printf("Failed to marshal Data: %v. Error: %v. Skipping jsonUnmarshalHook", data, err)
			return data, nil
		}

		res := reflect.New(to).Interface()
		err = json.Unmarshal(raw, &res)
		if err != nil {
			fmt.Printf("Failed to umarshal Data: %v. Error: %v. Skipping jsonUnmarshalHook", data, err)
			return data, nil
		}

		return res, nil
	}

	return data, nil
}

func decode_Config(input, result interface{}) error {
	config := &mapstructure.DecoderConfig{
		TagName:          "json",
		WeaklyTypedInput: true,
		Result:           result,
		DecodeHook: mapstructure.ComposeDecodeHookFunc(
			mapstructure.StringToTimeDurationHookFunc(),
			mapstructure.StringToSliceHookFunc(","),
			jsonUnmarshalerHookConfig,
		),
	}

	decoder, err := mapstructure.NewDecoder(config)
	if err != nil {
		return err
	}

	return decoder.Decode(input)
}

func join_Config(arr interface{}, sep string) string {
	listValue := reflect.ValueOf(arr)
	strs := make([]string, 0, listValue.Len())
	for i := 0; i < listValue.Len(); i++ {
		strs = append(strs, fmt.Sprintf("%v", listValue.Index(i)))
	}

	return strings.Join(strs, sep)
}

func testDecodeJson_Config(t *testing.T, val, result interface{}) {
	assert.NoError(t, decode_Config(val, result))
}

func testDecodeSlice_Config(t *testing.T, vStringSlice, result interface{}) {
	assert.NoError(t, decode_Config(vStringSlice, result))
}

func TestConfig_GetPFlagSet(t *testing.T) {
	val := Config{}
	cmdFlags := val.GetPFlagSet("")
	assert.True(t, cmdFlags.HasFlags())
}

func TestConfig_SetFlags(t *testing.T) {
	actual := Config{}
	cmdFlags := actual.GetPFlagSet("")
	assert.True(t, cmdFlags.HasFlags())

	t.Run("Test_ClientBaseConfig.endpoint", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("ClientBaseConfig.endpoint"); err == nil {
				assert.Equal(t, string(defaultConfig.ClientBaseConfig.Endpoint.String()), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := defaultConfig.ClientBaseConfig.Endpoint.String()

			cmdFlags.Set("ClientBaseConfig.endpoint", testValue)
			if vString, err := cmdFlags.GetString("ClientBaseConfig.endpoint"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.ClientBaseConfig.Endpoint)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_ClientBaseConfig.insecure", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vBool, err := cmdFlags.GetBool("ClientBaseConfig.insecure"); err == nil {
				assert.Equal(t, bool(defaultConfig.ClientBaseConfig.UseInsecureConnection), vBool)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("ClientBaseConfig.insecure", testValue)
			if vBool, err := cmdFlags.GetBool("ClientBaseConfig.insecure"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vBool), &actual.ClientBaseConfig.UseInsecureConnection)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_ClientBaseConfig.maxBackoffDelay", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("ClientBaseConfig.maxBackoffDelay"); err == nil {
				assert.Equal(t, string(defaultConfig.ClientBaseConfig.MaxBackoffDelay.String()), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := defaultConfig.ClientBaseConfig.MaxBackoffDelay.String()

			cmdFlags.Set("ClientBaseConfig.maxBackoffDelay", testValue)
			if vString, err := cmdFlags.GetString("ClientBaseConfig.maxBackoffDelay"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.ClientBaseConfig.MaxBackoffDelay)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_ClientBaseConfig.perRetryTimeout", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("ClientBaseConfig.perRetryTimeout"); err == nil {
				assert.Equal(t, string(defaultConfig.ClientBaseConfig.PerRetryTimeout.String()), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := defaultConfig.ClientBaseConfig.PerRetryTimeout.String()

			cmdFlags.Set("ClientBaseConfig.perRetryTimeout", testValue)
			if vString, err := cmdFlags.GetString("ClientBaseConfig.perRetryTimeout"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.ClientBaseConfig.PerRetryTimeout)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_ClientBaseConfig.maxRetries", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vInt, err := cmdFlags.GetInt("ClientBaseConfig.maxRetries"); err == nil {
				assert.Equal(t, int(defaultConfig.ClientBaseConfig.MaxRetries), vInt)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("ClientBaseConfig.maxRetries", testValue)
			if vInt, err := cmdFlags.GetInt("ClientBaseConfig.maxRetries"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vInt), &actual.ClientBaseConfig.MaxRetries)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_useAuth", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vBool, err := cmdFlags.GetBool("useAuth"); err == nil {
				assert.Equal(t, bool(defaultConfig.DeprecatedUseAuth), vBool)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("useAuth", testValue)
			if vBool, err := cmdFlags.GetBool("useAuth"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vBool), &actual.DeprecatedUseAuth)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_clientId", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("clientId"); err == nil {
				assert.Equal(t, string(defaultConfig.ClientID), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("clientId", testValue)
			if vString, err := cmdFlags.GetString("clientId"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.ClientID)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_clientSecretLocation", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("clientSecretLocation"); err == nil {
				assert.Equal(t, string(defaultConfig.ClientSecretLocation), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("clientSecretLocation", testValue)
			if vString, err := cmdFlags.GetString("clientSecretLocation"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.ClientSecretLocation)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_scopes", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vStringSlice, err := cmdFlags.GetStringSlice("scopes"); err == nil {
				assert.Equal(t, []string([]string{}), vStringSlice)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := join_Config("1,1", ",")

			cmdFlags.Set("scopes", testValue)
			if vStringSlice, err := cmdFlags.GetStringSlice("scopes"); err == nil {
				testDecodeSlice_Config(t, join_Config(vStringSlice, ","), &actual.Scopes)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_authorizationServerUrl", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("authorizationServerUrl"); err == nil {
				assert.Equal(t, string(defaultConfig.DeprecatedAuthorizationServerURL), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("authorizationServerUrl", testValue)
			if vString, err := cmdFlags.GetString("authorizationServerUrl"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.DeprecatedAuthorizationServerURL)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_tokenUrl", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("tokenUrl"); err == nil {
				assert.Equal(t, string(defaultConfig.TokenURL), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("tokenUrl", testValue)
			if vString, err := cmdFlags.GetString("tokenUrl"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.TokenURL)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_authorizationHeader", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("authorizationHeader"); err == nil {
				assert.Equal(t, string(defaultConfig.DeprecatedAuthorizationHeader), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("authorizationHeader", testValue)
			if vString, err := cmdFlags.GetString("authorizationHeader"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.DeprecatedAuthorizationHeader)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_pkceConfig.timeout", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("pkceConfig.timeout"); err == nil {
				assert.Equal(t, string(defaultConfig.PkceConfig.BrowserSessionTimeout.String()), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := defaultConfig.PkceConfig.BrowserSessionTimeout.String()

			cmdFlags.Set("pkceConfig.timeout", testValue)
			if vString, err := cmdFlags.GetString("pkceConfig.timeout"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.PkceConfig.BrowserSessionTimeout)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_pkceConfig.refreshTime", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("pkceConfig.refreshTime"); err == nil {
				assert.Equal(t, string(defaultConfig.PkceConfig.TokenRefreshGracePeriod.String()), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := defaultConfig.PkceConfig.TokenRefreshGracePeriod.String()

			cmdFlags.Set("pkceConfig.refreshTime", testValue)
			if vString, err := cmdFlags.GetString("pkceConfig.refreshTime"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.PkceConfig.TokenRefreshGracePeriod)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
}
