# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: admin/workflow.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from core import workflow_pb2 as core_dot_workflow__pb2
from admin import common_pb2 as admin_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='admin/workflow.proto',
  package='admin',
  syntax='proto3',
  serialized_pb=_b('\n\x14\x61\x64min/workflow.proto\x12\x05\x61\x64min\x1a\x13\x63ore/workflow.proto\x1a\x12\x61\x64min/common.proto\"j\n\x15WorkflowCreateRequest\x12\x1d\n\x02id\x18\x01 \x01(\x0b\x32\x11.admin.Identifier\x12\x0f\n\x07version\x18\x02 \x01(\t\x12!\n\x04spec\x18\x03 \x01(\x0b\x32\x13.admin.WorkflowSpec\"%\n\x16WorkflowCreateResponse\x12\x0b\n\x03urn\x18\x01 \x01(\t\"j\n\x08Workflow\x12\x1d\n\x02id\x18\x01 \x01(\x0b\x32\x11.admin.Identifier\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0b\n\x03urn\x18\x03 \x01(\t\x12!\n\x04spec\x18\x04 \x01(\x0b\x32\x13.admin.WorkflowSpec\"2\n\x0cWorkflowList\x12\"\n\tworkflows\x18\x01 \x03(\x0b\x32\x0f.admin.Workflow\"A\n\x0cWorkflowSpec\x12\x31\n\x11workflow_template\x18\x01 \x01(\x0b\x32\x16.core.WorkflowTemplateB\x07Z\x05\x61\x64minb\x06proto3')
  ,
  dependencies=[core_dot_workflow__pb2.DESCRIPTOR,admin_dot_common__pb2.DESCRIPTOR,])




_WORKFLOWCREATEREQUEST = _descriptor.Descriptor(
  name='WorkflowCreateRequest',
  full_name='admin.WorkflowCreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='admin.WorkflowCreateRequest.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='admin.WorkflowCreateRequest.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spec', full_name='admin.WorkflowCreateRequest.spec', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=178,
)


_WORKFLOWCREATERESPONSE = _descriptor.Descriptor(
  name='WorkflowCreateResponse',
  full_name='admin.WorkflowCreateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='urn', full_name='admin.WorkflowCreateResponse.urn', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=217,
)


_WORKFLOW = _descriptor.Descriptor(
  name='Workflow',
  full_name='admin.Workflow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='admin.Workflow.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='admin.Workflow.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='urn', full_name='admin.Workflow.urn', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spec', full_name='admin.Workflow.spec', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=325,
)


_WORKFLOWLIST = _descriptor.Descriptor(
  name='WorkflowList',
  full_name='admin.WorkflowList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workflows', full_name='admin.WorkflowList.workflows', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=377,
)


_WORKFLOWSPEC = _descriptor.Descriptor(
  name='WorkflowSpec',
  full_name='admin.WorkflowSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workflow_template', full_name='admin.WorkflowSpec.workflow_template', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=444,
)

_WORKFLOWCREATEREQUEST.fields_by_name['id'].message_type = admin_dot_common__pb2._IDENTIFIER
_WORKFLOWCREATEREQUEST.fields_by_name['spec'].message_type = _WORKFLOWSPEC
_WORKFLOW.fields_by_name['id'].message_type = admin_dot_common__pb2._IDENTIFIER
_WORKFLOW.fields_by_name['spec'].message_type = _WORKFLOWSPEC
_WORKFLOWLIST.fields_by_name['workflows'].message_type = _WORKFLOW
_WORKFLOWSPEC.fields_by_name['workflow_template'].message_type = core_dot_workflow__pb2._WORKFLOWTEMPLATE
DESCRIPTOR.message_types_by_name['WorkflowCreateRequest'] = _WORKFLOWCREATEREQUEST
DESCRIPTOR.message_types_by_name['WorkflowCreateResponse'] = _WORKFLOWCREATERESPONSE
DESCRIPTOR.message_types_by_name['Workflow'] = _WORKFLOW
DESCRIPTOR.message_types_by_name['WorkflowList'] = _WORKFLOWLIST
DESCRIPTOR.message_types_by_name['WorkflowSpec'] = _WORKFLOWSPEC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorkflowCreateRequest = _reflection.GeneratedProtocolMessageType('WorkflowCreateRequest', (_message.Message,), dict(
  DESCRIPTOR = _WORKFLOWCREATEREQUEST,
  __module__ = 'admin.workflow_pb2'
  # @@protoc_insertion_point(class_scope:admin.WorkflowCreateRequest)
  ))
_sym_db.RegisterMessage(WorkflowCreateRequest)

WorkflowCreateResponse = _reflection.GeneratedProtocolMessageType('WorkflowCreateResponse', (_message.Message,), dict(
  DESCRIPTOR = _WORKFLOWCREATERESPONSE,
  __module__ = 'admin.workflow_pb2'
  # @@protoc_insertion_point(class_scope:admin.WorkflowCreateResponse)
  ))
_sym_db.RegisterMessage(WorkflowCreateResponse)

Workflow = _reflection.GeneratedProtocolMessageType('Workflow', (_message.Message,), dict(
  DESCRIPTOR = _WORKFLOW,
  __module__ = 'admin.workflow_pb2'
  # @@protoc_insertion_point(class_scope:admin.Workflow)
  ))
_sym_db.RegisterMessage(Workflow)

WorkflowList = _reflection.GeneratedProtocolMessageType('WorkflowList', (_message.Message,), dict(
  DESCRIPTOR = _WORKFLOWLIST,
  __module__ = 'admin.workflow_pb2'
  # @@protoc_insertion_point(class_scope:admin.WorkflowList)
  ))
_sym_db.RegisterMessage(WorkflowList)

WorkflowSpec = _reflection.GeneratedProtocolMessageType('WorkflowSpec', (_message.Message,), dict(
  DESCRIPTOR = _WORKFLOWSPEC,
  __module__ = 'admin.workflow_pb2'
  # @@protoc_insertion_point(class_scope:admin.WorkflowSpec)
  ))
_sym_db.RegisterMessage(WorkflowSpec)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\005admin'))
# @@protoc_insertion_point(module_scope)
