// Code generated by mockery v1.0.1. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	service "github.com/flyteorg/flyteidl/gen/pb-go/flyteidl/service"
)

// AuthServiceClient is an autogenerated mock type for the AuthServiceClient type
type AuthServiceClient struct {
	mock.Mock
}

type AuthServiceClient_FlyteClient struct {
	*mock.Call
}

func (_m AuthServiceClient_FlyteClient) Return(_a0 *service.FlyteClientResponse, _a1 error) *AuthServiceClient_FlyteClient {
	return &AuthServiceClient_FlyteClient{Call: _m.Call.Return(_a0, _a1)}
}

func (_m *AuthServiceClient) OnFlyteClient(ctx context.Context, in *service.FlyteClientRequest, opts ...grpc.CallOption) *AuthServiceClient_FlyteClient {
	c := _m.On("FlyteClient", ctx, in, opts)
	return &AuthServiceClient_FlyteClient{Call: c}
}

func (_m *AuthServiceClient) OnFlyteClientMatch(matchers ...interface{}) *AuthServiceClient_FlyteClient {
	c := _m.On("FlyteClient", matchers...)
	return &AuthServiceClient_FlyteClient{Call: c}
}

// FlyteClient provides a mock function with given fields: ctx, in, opts
func (_m *AuthServiceClient) FlyteClient(ctx context.Context, in *service.FlyteClientRequest, opts ...grpc.CallOption) (*service.FlyteClientResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *service.FlyteClientResponse
	if rf, ok := ret.Get(0).(func(context.Context, *service.FlyteClientRequest, ...grpc.CallOption) *service.FlyteClientResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.FlyteClientResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service.FlyteClientRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type AuthServiceClient_OAuth2Metadata struct {
	*mock.Call
}

func (_m AuthServiceClient_OAuth2Metadata) Return(_a0 *service.OAuth2MetadataResponse, _a1 error) *AuthServiceClient_OAuth2Metadata {
	return &AuthServiceClient_OAuth2Metadata{Call: _m.Call.Return(_a0, _a1)}
}

func (_m *AuthServiceClient) OnOAuth2Metadata(ctx context.Context, in *service.OAuth2MetadataRequest, opts ...grpc.CallOption) *AuthServiceClient_OAuth2Metadata {
	c := _m.On("OAuth2Metadata", ctx, in, opts)
	return &AuthServiceClient_OAuth2Metadata{Call: c}
}

func (_m *AuthServiceClient) OnOAuth2MetadataMatch(matchers ...interface{}) *AuthServiceClient_OAuth2Metadata {
	c := _m.On("OAuth2Metadata", matchers...)
	return &AuthServiceClient_OAuth2Metadata{Call: c}
}

// OAuth2Metadata provides a mock function with given fields: ctx, in, opts
func (_m *AuthServiceClient) OAuth2Metadata(ctx context.Context, in *service.OAuth2MetadataRequest, opts ...grpc.CallOption) (*service.OAuth2MetadataResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *service.OAuth2MetadataResponse
	if rf, ok := ret.Get(0).(func(context.Context, *service.OAuth2MetadataRequest, ...grpc.CallOption) *service.OAuth2MetadataResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.OAuth2MetadataResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service.OAuth2MetadataRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type AuthServiceClient_UserInfo struct {
	*mock.Call
}

func (_m AuthServiceClient_UserInfo) Return(_a0 *service.UserInfoResponse, _a1 error) *AuthServiceClient_UserInfo {
	return &AuthServiceClient_UserInfo{Call: _m.Call.Return(_a0, _a1)}
}

func (_m *AuthServiceClient) OnUserInfo(ctx context.Context, in *service.UserInfoRequest, opts ...grpc.CallOption) *AuthServiceClient_UserInfo {
	c := _m.On("UserInfo", ctx, in, opts)
	return &AuthServiceClient_UserInfo{Call: c}
}

func (_m *AuthServiceClient) OnUserInfoMatch(matchers ...interface{}) *AuthServiceClient_UserInfo {
	c := _m.On("UserInfo", matchers...)
	return &AuthServiceClient_UserInfo{Call: c}
}

// UserInfo provides a mock function with given fields: ctx, in, opts
func (_m *AuthServiceClient) UserInfo(ctx context.Context, in *service.UserInfoRequest, opts ...grpc.CallOption) (*service.UserInfoResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *service.UserInfoResponse
	if rf, ok := ret.Get(0).(func(context.Context, *service.UserInfoRequest, ...grpc.CallOption) *service.UserInfoResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.UserInfoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service.UserInfoRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
