// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core/workflow.proto

package core

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import duration "github.com/golang/protobuf/ptypes/duration"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Defines a condition and the execution unit that should be executed if the condition is satisfied.
type IfBlock struct {
	Condition            *BooleanExpression `protobuf:"bytes,1,opt,name=condition" json:"condition,omitempty"`
	ThenNode             *Node              `protobuf:"bytes,2,opt,name=then_node,json=thenNode" json:"then_node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *IfBlock) Reset()         { *m = IfBlock{} }
func (m *IfBlock) String() string { return proto.CompactTextString(m) }
func (*IfBlock) ProtoMessage()    {}
func (*IfBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_45e9a769c873e4ad, []int{0}
}
func (m *IfBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IfBlock.Unmarshal(m, b)
}
func (m *IfBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IfBlock.Marshal(b, m, deterministic)
}
func (dst *IfBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IfBlock.Merge(dst, src)
}
func (m *IfBlock) XXX_Size() int {
	return xxx_messageInfo_IfBlock.Size(m)
}
func (m *IfBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_IfBlock.DiscardUnknown(m)
}

var xxx_messageInfo_IfBlock proto.InternalMessageInfo

func (m *IfBlock) GetCondition() *BooleanExpression {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *IfBlock) GetThenNode() *Node {
	if m != nil {
		return m.ThenNode
	}
	return nil
}

// Defines a series of if/else blocks. The first branch whose condition evaluates to true is the one to execute.
// If no conditions were satisfied, the else_node will be executed.
type IfElseBlock struct {
	// +required. First condition to evaluate.
	Case *IfBlock `protobuf:"bytes,1,opt,name=case" json:"case,omitempty"`
	// +optional. Additional branches to evaluate.
	Other []*IfBlock `protobuf:"bytes,2,rep,name=other" json:"other,omitempty"`
	// +required.
	//
	// Types that are valid to be assigned to Default:
	//	*IfElseBlock_ElseNode
	//	*IfElseBlock_Error
	Default              isIfElseBlock_Default `protobuf_oneof:"default"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *IfElseBlock) Reset()         { *m = IfElseBlock{} }
func (m *IfElseBlock) String() string { return proto.CompactTextString(m) }
func (*IfElseBlock) ProtoMessage()    {}
func (*IfElseBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_45e9a769c873e4ad, []int{1}
}
func (m *IfElseBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IfElseBlock.Unmarshal(m, b)
}
func (m *IfElseBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IfElseBlock.Marshal(b, m, deterministic)
}
func (dst *IfElseBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IfElseBlock.Merge(dst, src)
}
func (m *IfElseBlock) XXX_Size() int {
	return xxx_messageInfo_IfElseBlock.Size(m)
}
func (m *IfElseBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_IfElseBlock.DiscardUnknown(m)
}

var xxx_messageInfo_IfElseBlock proto.InternalMessageInfo

type isIfElseBlock_Default interface {
	isIfElseBlock_Default()
}

type IfElseBlock_ElseNode struct {
	ElseNode *Node `protobuf:"bytes,3,opt,name=else_node,json=elseNode,oneof"`
}
type IfElseBlock_Error struct {
	Error *Error `protobuf:"bytes,4,opt,name=error,oneof"`
}

func (*IfElseBlock_ElseNode) isIfElseBlock_Default() {}
func (*IfElseBlock_Error) isIfElseBlock_Default()    {}

func (m *IfElseBlock) GetDefault() isIfElseBlock_Default {
	if m != nil {
		return m.Default
	}
	return nil
}

func (m *IfElseBlock) GetCase() *IfBlock {
	if m != nil {
		return m.Case
	}
	return nil
}

func (m *IfElseBlock) GetOther() []*IfBlock {
	if m != nil {
		return m.Other
	}
	return nil
}

func (m *IfElseBlock) GetElseNode() *Node {
	if x, ok := m.GetDefault().(*IfElseBlock_ElseNode); ok {
		return x.ElseNode
	}
	return nil
}

func (m *IfElseBlock) GetError() *Error {
	if x, ok := m.GetDefault().(*IfElseBlock_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*IfElseBlock) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _IfElseBlock_OneofMarshaler, _IfElseBlock_OneofUnmarshaler, _IfElseBlock_OneofSizer, []interface{}{
		(*IfElseBlock_ElseNode)(nil),
		(*IfElseBlock_Error)(nil),
	}
}

func _IfElseBlock_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*IfElseBlock)
	// default
	switch x := m.Default.(type) {
	case *IfElseBlock_ElseNode:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ElseNode); err != nil {
			return err
		}
	case *IfElseBlock_Error:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("IfElseBlock.Default has unexpected type %T", x)
	}
	return nil
}

func _IfElseBlock_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*IfElseBlock)
	switch tag {
	case 3: // default.else_node
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Node)
		err := b.DecodeMessage(msg)
		m.Default = &IfElseBlock_ElseNode{msg}
		return true, err
	case 4: // default.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Error)
		err := b.DecodeMessage(msg)
		m.Default = &IfElseBlock_Error{msg}
		return true, err
	default:
		return false, nil
	}
}

func _IfElseBlock_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*IfElseBlock)
	// default
	switch x := m.Default.(type) {
	case *IfElseBlock_ElseNode:
		s := proto.Size(x.ElseNode)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *IfElseBlock_Error:
		s := proto.Size(x.Error)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// BranchNode is a special node that alter the flow of the workflow graph. It allows the control flow to branch at
// runtime based on a series of conditions that get evaluated on various parameters (e.g. inputs, primtives).
type BranchNode struct {
	// +required
	IfElse               *IfElseBlock `protobuf:"bytes,2,opt,name=if_else,json=ifElse" json:"if_else,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BranchNode) Reset()         { *m = BranchNode{} }
func (m *BranchNode) String() string { return proto.CompactTextString(m) }
func (*BranchNode) ProtoMessage()    {}
func (*BranchNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_45e9a769c873e4ad, []int{2}
}
func (m *BranchNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BranchNode.Unmarshal(m, b)
}
func (m *BranchNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BranchNode.Marshal(b, m, deterministic)
}
func (dst *BranchNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BranchNode.Merge(dst, src)
}
func (m *BranchNode) XXX_Size() int {
	return xxx_messageInfo_BranchNode.Size(m)
}
func (m *BranchNode) XXX_DiscardUnknown() {
	xxx_messageInfo_BranchNode.DiscardUnknown(m)
}

var xxx_messageInfo_BranchNode proto.InternalMessageInfo

func (m *BranchNode) GetIfElse() *IfElseBlock {
	if m != nil {
		return m.IfElse
	}
	return nil
}

// Refers to the task that the Node is to execute.
type TaskNode struct {
	// Types that are valid to be assigned to Reference:
	//	*TaskNode_ReferenceId
	Reference            isTaskNode_Reference `protobuf_oneof:"reference"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TaskNode) Reset()         { *m = TaskNode{} }
func (m *TaskNode) String() string { return proto.CompactTextString(m) }
func (*TaskNode) ProtoMessage()    {}
func (*TaskNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_45e9a769c873e4ad, []int{3}
}
func (m *TaskNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskNode.Unmarshal(m, b)
}
func (m *TaskNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskNode.Marshal(b, m, deterministic)
}
func (dst *TaskNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskNode.Merge(dst, src)
}
func (m *TaskNode) XXX_Size() int {
	return xxx_messageInfo_TaskNode.Size(m)
}
func (m *TaskNode) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskNode.DiscardUnknown(m)
}

var xxx_messageInfo_TaskNode proto.InternalMessageInfo

type isTaskNode_Reference interface {
	isTaskNode_Reference()
}

type TaskNode_ReferenceId struct {
	ReferenceId string `protobuf:"bytes,1,opt,name=reference_id,json=referenceId,oneof"`
}

func (*TaskNode_ReferenceId) isTaskNode_Reference() {}

func (m *TaskNode) GetReference() isTaskNode_Reference {
	if m != nil {
		return m.Reference
	}
	return nil
}

func (m *TaskNode) GetReferenceId() string {
	if x, ok := m.GetReference().(*TaskNode_ReferenceId); ok {
		return x.ReferenceId
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*TaskNode) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _TaskNode_OneofMarshaler, _TaskNode_OneofUnmarshaler, _TaskNode_OneofSizer, []interface{}{
		(*TaskNode_ReferenceId)(nil),
	}
}

func _TaskNode_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*TaskNode)
	// reference
	switch x := m.Reference.(type) {
	case *TaskNode_ReferenceId:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.ReferenceId)
	case nil:
	default:
		return fmt.Errorf("TaskNode.Reference has unexpected type %T", x)
	}
	return nil
}

func _TaskNode_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*TaskNode)
	switch tag {
	case 1: // reference.reference_id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Reference = &TaskNode_ReferenceId{x}
		return true, err
	default:
		return false, nil
	}
}

func _TaskNode_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*TaskNode)
	// reference
	switch x := m.Reference.(type) {
	case *TaskNode_ReferenceId:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.ReferenceId)))
		n += len(x.ReferenceId)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Refers to a the workflow the node is to execute.
type WorkflowNode struct {
	// Types that are valid to be assigned to Reference:
	//	*WorkflowNode_LaunchPlanReferenceId
	//	*WorkflowNode_WorkflowTemplate
	Reference            isWorkflowNode_Reference `protobuf_oneof:"reference"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *WorkflowNode) Reset()         { *m = WorkflowNode{} }
func (m *WorkflowNode) String() string { return proto.CompactTextString(m) }
func (*WorkflowNode) ProtoMessage()    {}
func (*WorkflowNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_45e9a769c873e4ad, []int{4}
}
func (m *WorkflowNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowNode.Unmarshal(m, b)
}
func (m *WorkflowNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowNode.Marshal(b, m, deterministic)
}
func (dst *WorkflowNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowNode.Merge(dst, src)
}
func (m *WorkflowNode) XXX_Size() int {
	return xxx_messageInfo_WorkflowNode.Size(m)
}
func (m *WorkflowNode) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowNode.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowNode proto.InternalMessageInfo

type isWorkflowNode_Reference interface {
	isWorkflowNode_Reference()
}

type WorkflowNode_LaunchPlanReferenceId struct {
	LaunchPlanReferenceId string `protobuf:"bytes,1,opt,name=launch_plan_reference_id,json=launchPlanReferenceId,oneof"`
}
type WorkflowNode_WorkflowTemplate struct {
	WorkflowTemplate *WorkflowTemplate `protobuf:"bytes,2,opt,name=workflow_template,json=workflowTemplate,oneof"`
}

func (*WorkflowNode_LaunchPlanReferenceId) isWorkflowNode_Reference() {}
func (*WorkflowNode_WorkflowTemplate) isWorkflowNode_Reference()      {}

func (m *WorkflowNode) GetReference() isWorkflowNode_Reference {
	if m != nil {
		return m.Reference
	}
	return nil
}

func (m *WorkflowNode) GetLaunchPlanReferenceId() string {
	if x, ok := m.GetReference().(*WorkflowNode_LaunchPlanReferenceId); ok {
		return x.LaunchPlanReferenceId
	}
	return ""
}

func (m *WorkflowNode) GetWorkflowTemplate() *WorkflowTemplate {
	if x, ok := m.GetReference().(*WorkflowNode_WorkflowTemplate); ok {
		return x.WorkflowTemplate
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*WorkflowNode) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _WorkflowNode_OneofMarshaler, _WorkflowNode_OneofUnmarshaler, _WorkflowNode_OneofSizer, []interface{}{
		(*WorkflowNode_LaunchPlanReferenceId)(nil),
		(*WorkflowNode_WorkflowTemplate)(nil),
	}
}

func _WorkflowNode_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*WorkflowNode)
	// reference
	switch x := m.Reference.(type) {
	case *WorkflowNode_LaunchPlanReferenceId:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.LaunchPlanReferenceId)
	case *WorkflowNode_WorkflowTemplate:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.WorkflowTemplate); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("WorkflowNode.Reference has unexpected type %T", x)
	}
	return nil
}

func _WorkflowNode_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*WorkflowNode)
	switch tag {
	case 1: // reference.launch_plan_reference_id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Reference = &WorkflowNode_LaunchPlanReferenceId{x}
		return true, err
	case 2: // reference.workflow_template
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WorkflowTemplate)
		err := b.DecodeMessage(msg)
		m.Reference = &WorkflowNode_WorkflowTemplate{msg}
		return true, err
	default:
		return false, nil
	}
}

func _WorkflowNode_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*WorkflowNode)
	// reference
	switch x := m.Reference.(type) {
	case *WorkflowNode_LaunchPlanReferenceId:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.LaunchPlanReferenceId)))
		n += len(x.LaunchPlanReferenceId)
	case *WorkflowNode_WorkflowTemplate:
		s := proto.Size(x.WorkflowTemplate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Defines extra information about the Node.
type NodeMetadata struct {
	// A friendly name for the Node
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The overall timeout of a task.
	Timeout *duration.Duration `protobuf:"bytes,4,opt,name=timeout" json:"timeout,omitempty"`
	// Number of retries per task.
	Retries              *RetryStrategy `protobuf:"bytes,5,opt,name=retries" json:"retries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NodeMetadata) Reset()         { *m = NodeMetadata{} }
func (m *NodeMetadata) String() string { return proto.CompactTextString(m) }
func (*NodeMetadata) ProtoMessage()    {}
func (*NodeMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_45e9a769c873e4ad, []int{5}
}
func (m *NodeMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeMetadata.Unmarshal(m, b)
}
func (m *NodeMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeMetadata.Marshal(b, m, deterministic)
}
func (dst *NodeMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeMetadata.Merge(dst, src)
}
func (m *NodeMetadata) XXX_Size() int {
	return xxx_messageInfo_NodeMetadata.Size(m)
}
func (m *NodeMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_NodeMetadata proto.InternalMessageInfo

func (m *NodeMetadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeMetadata) GetTimeout() *duration.Duration {
	if m != nil {
		return m.Timeout
	}
	return nil
}

func (m *NodeMetadata) GetRetries() *RetryStrategy {
	if m != nil {
		return m.Retries
	}
	return nil
}

// Links a variable to an alias.
type Alias struct {
	// Must match one of the output variable names on a node.
	Var string `protobuf:"bytes,1,opt,name=var" json:"var,omitempty"`
	// A workflow-level unique alias that downstream nodes can refer to in their input.
	Alias                string   `protobuf:"bytes,2,opt,name=alias" json:"alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Alias) Reset()         { *m = Alias{} }
func (m *Alias) String() string { return proto.CompactTextString(m) }
func (*Alias) ProtoMessage()    {}
func (*Alias) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_45e9a769c873e4ad, []int{6}
}
func (m *Alias) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Alias.Unmarshal(m, b)
}
func (m *Alias) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Alias.Marshal(b, m, deterministic)
}
func (dst *Alias) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Alias.Merge(dst, src)
}
func (m *Alias) XXX_Size() int {
	return xxx_messageInfo_Alias.Size(m)
}
func (m *Alias) XXX_DiscardUnknown() {
	xxx_messageInfo_Alias.DiscardUnknown(m)
}

var xxx_messageInfo_Alias proto.InternalMessageInfo

func (m *Alias) GetVar() string {
	if m != nil {
		return m.Var
	}
	return ""
}

func (m *Alias) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

// A Workflow graph Node. One unit of execution in the graph. Each node can be linked to a Task, a Workflow or a branch
// node.
type Node struct {
	// A workflow-level unique identifier that identifies this node in the workflow. "inputs" and "outputs" are reserved
	// node ids that cannot be used by other nodes.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Extra metadata about the node.
	Metadata *NodeMetadata `protobuf:"bytes,2,opt,name=metadata" json:"metadata,omitempty"`
	// Specifies how to bind the underlying interface's inputs. All required inputs specified in the underlying interface
	// must be fullfilled.
	Inputs []*Binding `protobuf:"bytes,3,rep,name=inputs" json:"inputs,omitempty"`
	// +optional Specifies execution depdendency for this node ensuring it will only get scheduled to run after all its
	// upstream nodes have completed. This node will have an implicit depdendency on any node that appears in inputs
	// field.
	UpstreamNodeIds []string `protobuf:"bytes,4,rep,name=upstream_node_ids,json=upstreamNodeIds" json:"upstream_node_ids,omitempty"`
	// +optional. A node can define aliases for a subset of its outputs. This is particularly useful if different nodes
	// need to conform to the same interface (e.g. all branches in a branch node). Downstream nodes must refer to this
	// nodes outputs using the alias if one's specified.
	OutputAliases []*Alias `protobuf:"bytes,5,rep,name=output_aliases,json=outputAliases" json:"output_aliases,omitempty"`
	// Information about the target to execute in this node.
	//
	// Types that are valid to be assigned to Target:
	//	*Node_TaskNode
	//	*Node_WorkflowNode
	//	*Node_BranchNode
	Target               isNode_Target `protobuf_oneof:"target"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_45e9a769c873e4ad, []int{7}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

type isNode_Target interface {
	isNode_Target()
}

type Node_TaskNode struct {
	TaskNode *TaskNode `protobuf:"bytes,6,opt,name=task_node,json=taskNode,oneof"`
}
type Node_WorkflowNode struct {
	WorkflowNode *WorkflowNode `protobuf:"bytes,7,opt,name=workflow_node,json=workflowNode,oneof"`
}
type Node_BranchNode struct {
	BranchNode *BranchNode `protobuf:"bytes,8,opt,name=branch_node,json=branchNode,oneof"`
}

func (*Node_TaskNode) isNode_Target()     {}
func (*Node_WorkflowNode) isNode_Target() {}
func (*Node_BranchNode) isNode_Target()   {}

func (m *Node) GetTarget() isNode_Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Node) GetMetadata() *NodeMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Node) GetInputs() []*Binding {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *Node) GetUpstreamNodeIds() []string {
	if m != nil {
		return m.UpstreamNodeIds
	}
	return nil
}

func (m *Node) GetOutputAliases() []*Alias {
	if m != nil {
		return m.OutputAliases
	}
	return nil
}

func (m *Node) GetTaskNode() *TaskNode {
	if x, ok := m.GetTarget().(*Node_TaskNode); ok {
		return x.TaskNode
	}
	return nil
}

func (m *Node) GetWorkflowNode() *WorkflowNode {
	if x, ok := m.GetTarget().(*Node_WorkflowNode); ok {
		return x.WorkflowNode
	}
	return nil
}

func (m *Node) GetBranchNode() *BranchNode {
	if x, ok := m.GetTarget().(*Node_BranchNode); ok {
		return x.BranchNode
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Node) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Node_OneofMarshaler, _Node_OneofUnmarshaler, _Node_OneofSizer, []interface{}{
		(*Node_TaskNode)(nil),
		(*Node_WorkflowNode)(nil),
		(*Node_BranchNode)(nil),
	}
}

func _Node_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Node)
	// target
	switch x := m.Target.(type) {
	case *Node_TaskNode:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TaskNode); err != nil {
			return err
		}
	case *Node_WorkflowNode:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.WorkflowNode); err != nil {
			return err
		}
	case *Node_BranchNode:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BranchNode); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Node.Target has unexpected type %T", x)
	}
	return nil
}

func _Node_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Node)
	switch tag {
	case 6: // target.task_node
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TaskNode)
		err := b.DecodeMessage(msg)
		m.Target = &Node_TaskNode{msg}
		return true, err
	case 7: // target.workflow_node
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WorkflowNode)
		err := b.DecodeMessage(msg)
		m.Target = &Node_WorkflowNode{msg}
		return true, err
	case 8: // target.branch_node
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BranchNode)
		err := b.DecodeMessage(msg)
		m.Target = &Node_BranchNode{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Node_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Node)
	// target
	switch x := m.Target.(type) {
	case *Node_TaskNode:
		s := proto.Size(x.TaskNode)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Node_WorkflowNode:
		s := proto.Size(x.WorkflowNode)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Node_BranchNode:
		s := proto.Size(x.BranchNode)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Metadata for the entire workflow.
type WorkflowMetadata struct {
	ExecutionRole        string   `protobuf:"bytes,1,opt,name=execution_role,json=executionRole" json:"execution_role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkflowMetadata) Reset()         { *m = WorkflowMetadata{} }
func (m *WorkflowMetadata) String() string { return proto.CompactTextString(m) }
func (*WorkflowMetadata) ProtoMessage()    {}
func (*WorkflowMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_45e9a769c873e4ad, []int{8}
}
func (m *WorkflowMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowMetadata.Unmarshal(m, b)
}
func (m *WorkflowMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowMetadata.Marshal(b, m, deterministic)
}
func (dst *WorkflowMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowMetadata.Merge(dst, src)
}
func (m *WorkflowMetadata) XXX_Size() int {
	return xxx_messageInfo_WorkflowMetadata.Size(m)
}
func (m *WorkflowMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowMetadata proto.InternalMessageInfo

func (m *WorkflowMetadata) GetExecutionRole() string {
	if m != nil {
		return m.ExecutionRole
	}
	return ""
}

// Flyte Workflow Structure that encapsulates task, branch and subworkflow nodes to form a statically analyzable,
// directed acyclic graph.
type WorkflowTemplate struct {
	// This is an autogenerated id by the system. The id is globally unique across the system.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Extra metadata about the workflow.
	Metadata *WorkflowMetadata `protobuf:"bytes,2,opt,name=metadata" json:"metadata,omitempty"`
	// Defines a strongly typed interface for the Workflow. This can include some optional parameters.
	Interface *TypedInterface `protobuf:"bytes,3,opt,name=interface" json:"interface,omitempty"`
	// A list of nodes. In addition, "globals" is a special reserved node id that can be used to consume workflow inputs.
	Nodes []*Node `protobuf:"bytes,4,rep,name=nodes" json:"nodes,omitempty"`
	// A list of output bindings that specify how to construct workflow outputs. Bindings can pull node outputs or
	// specify literals. All workflow outputs specified in the interface field must be bound in order for the workflow
	// to be validated. A workflow has an implicit depdendency on all of its nodes to execute successfully in order to
	// bind final outputs.
	Outputs []*Binding `protobuf:"bytes,5,rep,name=outputs" json:"outputs,omitempty"`
	// +optional A catch-all node. This node is executed whenever the execution engine determines the workflow has failed.
	// The interface of this node must match the Workflow interface with an additional input named "error" of type
	// pb.lyft.flyte.core.Error.
	FailureNode          *Node    `protobuf:"bytes,6,opt,name=failure_node,json=failureNode" json:"failure_node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkflowTemplate) Reset()         { *m = WorkflowTemplate{} }
func (m *WorkflowTemplate) String() string { return proto.CompactTextString(m) }
func (*WorkflowTemplate) ProtoMessage()    {}
func (*WorkflowTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_45e9a769c873e4ad, []int{9}
}
func (m *WorkflowTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowTemplate.Unmarshal(m, b)
}
func (m *WorkflowTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowTemplate.Marshal(b, m, deterministic)
}
func (dst *WorkflowTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowTemplate.Merge(dst, src)
}
func (m *WorkflowTemplate) XXX_Size() int {
	return xxx_messageInfo_WorkflowTemplate.Size(m)
}
func (m *WorkflowTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowTemplate proto.InternalMessageInfo

func (m *WorkflowTemplate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WorkflowTemplate) GetMetadata() *WorkflowMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *WorkflowTemplate) GetInterface() *TypedInterface {
	if m != nil {
		return m.Interface
	}
	return nil
}

func (m *WorkflowTemplate) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *WorkflowTemplate) GetOutputs() []*Binding {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *WorkflowTemplate) GetFailureNode() *Node {
	if m != nil {
		return m.FailureNode
	}
	return nil
}

func init() {
	proto.RegisterType((*IfBlock)(nil), "core.IfBlock")
	proto.RegisterType((*IfElseBlock)(nil), "core.IfElseBlock")
	proto.RegisterType((*BranchNode)(nil), "core.BranchNode")
	proto.RegisterType((*TaskNode)(nil), "core.TaskNode")
	proto.RegisterType((*WorkflowNode)(nil), "core.WorkflowNode")
	proto.RegisterType((*NodeMetadata)(nil), "core.NodeMetadata")
	proto.RegisterType((*Alias)(nil), "core.Alias")
	proto.RegisterType((*Node)(nil), "core.Node")
	proto.RegisterType((*WorkflowMetadata)(nil), "core.WorkflowMetadata")
	proto.RegisterType((*WorkflowTemplate)(nil), "core.WorkflowTemplate")
}

func init() { proto.RegisterFile("core/workflow.proto", fileDescriptor_workflow_45e9a769c873e4ad) }

var fileDescriptor_workflow_45e9a769c873e4ad = []byte{
	// 786 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x55, 0xdd, 0x6e, 0x23, 0x35,
	0x14, 0xce, 0x7f, 0x32, 0x27, 0x69, 0x49, 0xbd, 0x05, 0xc2, 0x5e, 0xa0, 0x32, 0x08, 0xed, 0xb2,
	0x52, 0x53, 0xa9, 0x15, 0x12, 0x95, 0xb8, 0xd9, 0x88, 0x4a, 0xc9, 0xc5, 0x22, 0x64, 0x56, 0x42,
	0xe2, 0x66, 0xe4, 0xce, 0x9c, 0x49, 0xad, 0x3a, 0xf6, 0xc8, 0xe3, 0xa1, 0xdb, 0x7b, 0xc4, 0x5b,
	0xf0, 0x0e, 0x3c, 0x1d, 0xd7, 0xc8, 0x7f, 0x93, 0x6c, 0xbb, 0x77, 0xf6, 0xf9, 0xce, 0x77, 0x7e,
	0x3f, 0xcf, 0xc0, 0x8b, 0x5c, 0x69, 0xbc, 0x78, 0x50, 0xfa, 0xbe, 0x14, 0xea, 0x61, 0x59, 0x69,
	0x65, 0x14, 0x19, 0x58, 0xe3, 0xcb, 0x53, 0x07, 0x71, 0x69, 0x50, 0x97, 0x2c, 0x47, 0x8f, 0xbd,
	0xf4, 0x04, 0xc1, 0x0d, 0x6a, 0x26, 0xea, 0x60, 0x9c, 0x3b, 0xa3, 0x79, 0xac, 0x30, 0x5a, 0x3c,
	0x39, 0x57, 0xb2, 0xe0, 0x86, 0x2b, 0x19, 0xac, 0x5f, 0x6f, 0x95, 0xda, 0x0a, 0xbc, 0x70, 0xb7,
	0xdb, 0xa6, 0xbc, 0x28, 0x1a, 0xcd, 0xf6, 0x78, 0xca, 0x61, 0xbc, 0x29, 0x57, 0x42, 0xe5, 0xf7,
	0xe4, 0x07, 0x48, 0x5a, 0xf6, 0xa2, 0x7b, 0xd6, 0x7d, 0x3d, 0xbd, 0xfc, 0x72, 0x69, 0x83, 0x2e,
	0x57, 0x4a, 0x09, 0x64, 0xf2, 0xe6, 0x43, 0xa5, 0xb1, 0xae, 0xb9, 0x92, 0x74, 0xef, 0x49, 0x5e,
	0x41, 0x62, 0xee, 0x50, 0x66, 0x52, 0x15, 0xb8, 0xe8, 0x39, 0x1a, 0x78, 0xda, 0x2f, 0xaa, 0x40,
	0x3a, 0xb1, 0xa0, 0x3d, 0xa5, 0xff, 0x76, 0x61, 0xba, 0x29, 0x6f, 0x44, 0x8d, 0x3e, 0xdf, 0x37,
	0x30, 0xc8, 0x59, 0x8d, 0x21, 0xd5, 0x91, 0xe7, 0x84, 0x62, 0xa8, 0x83, 0xc8, 0xb7, 0x30, 0x54,
	0xe6, 0x0e, 0xf5, 0xa2, 0x77, 0xd6, 0x7f, 0xee, 0xe3, 0x31, 0xf2, 0x3d, 0x24, 0x28, 0x6a, 0xf4,
	0x05, 0xf4, 0x9f, 0x16, 0xb0, 0xee, 0xd0, 0x89, 0x85, 0xed, 0xd9, 0xc6, 0x43, 0xad, 0x95, 0x5e,
	0x0c, 0x9c, 0xdb, 0xd4, 0xbb, 0xdd, 0x58, 0xd3, 0xba, 0x43, 0x3d, 0xb6, 0x4a, 0x60, 0x5c, 0x60,
	0xc9, 0x1a, 0x61, 0xd2, 0x1f, 0x01, 0x56, 0x9a, 0xc9, 0xfc, 0xce, 0xb1, 0xdf, 0xc0, 0x98, 0x97,
	0x99, 0x0d, 0x16, 0xfa, 0x3c, 0x89, 0xf5, 0xb4, 0x4d, 0xd1, 0x11, 0x77, 0x97, 0xf4, 0x27, 0x98,
	0xbc, 0x67, 0xf5, 0x7d, 0xc8, 0x3a, 0xd3, 0x58, 0xa2, 0x46, 0x99, 0x63, 0xc6, 0x0b, 0xd7, 0x70,
	0xb2, 0xee, 0xd0, 0x69, 0x6b, 0xdd, 0x14, 0xab, 0x29, 0x24, 0xed, 0x35, 0xfd, 0xa7, 0x0b, 0xb3,
	0xdf, 0x83, 0x42, 0x5c, 0x88, 0x6b, 0x58, 0x08, 0xd6, 0xc8, 0xfc, 0x2e, 0xab, 0x04, 0x93, 0xd9,
	0x27, 0xc3, 0x7d, 0xee, 0x3d, 0x7e, 0x15, 0x4c, 0xd2, 0x7d, 0x60, 0x72, 0x03, 0x27, 0x51, 0x6c,
	0x99, 0xc1, 0x5d, 0x25, 0x98, 0x89, 0xf5, 0x7f, 0xe1, 0xeb, 0x8f, 0x99, 0xde, 0x07, 0x74, 0xdd,
	0xa1, 0xf3, 0x87, 0x27, 0xb6, 0x8f, 0xeb, 0xfb, 0xbb, 0x0b, 0x33, 0x5b, 0xd7, 0x3b, 0x34, 0xac,
	0x60, 0x86, 0x11, 0x02, 0x03, 0xc9, 0x76, 0x7e, 0x97, 0x09, 0x75, 0x67, 0x72, 0x05, 0x63, 0xc3,
	0x77, 0xa8, 0x1a, 0x13, 0xc6, 0xfd, 0xd5, 0xd2, 0x8b, 0x71, 0x19, 0xc5, 0xb8, 0xfc, 0x39, 0x88,
	0x91, 0x46, 0x4f, 0x72, 0x0e, 0x63, 0x8d, 0x46, 0x73, 0xac, 0x17, 0x43, 0x47, 0x7a, 0xe1, 0x6b,
	0xa4, 0x68, 0xf4, 0xe3, 0x6f, 0x46, 0x33, 0x83, 0xdb, 0x47, 0x1a, 0x7d, 0xd2, 0x0b, 0x18, 0xbe,
	0x15, 0x9c, 0xd5, 0x64, 0x0e, 0xfd, 0x3f, 0x99, 0x0e, 0xf9, 0xed, 0x91, 0x9c, 0xc2, 0x90, 0x59,
	0xc8, 0xf5, 0x9a, 0x50, 0x7f, 0x49, 0xff, 0xeb, 0xc1, 0xc0, 0x4d, 0xf4, 0x18, 0x7a, 0x71, 0x76,
	0xb4, 0xc7, 0x0b, 0xb2, 0x84, 0xc9, 0x2e, 0x74, 0x13, 0xa6, 0x43, 0xf6, 0x22, 0x8a, 0x7d, 0xd2,
	0xd6, 0x87, 0x7c, 0x07, 0x23, 0x2e, 0xab, 0xc6, 0xd4, 0x8b, 0xfe, 0xa1, 0x36, 0x57, 0x5c, 0x16,
	0x5c, 0x6e, 0x69, 0x00, 0xc9, 0x1b, 0x38, 0x69, 0xaa, 0xda, 0x68, 0x64, 0x3b, 0x27, 0xd0, 0x8c,
	0x17, 0xf5, 0x62, 0x70, 0xd6, 0x7f, 0x9d, 0xd0, 0xcf, 0x22, 0x60, 0x33, 0x6c, 0x8a, 0x9a, 0x5c,
	0xc2, 0xb1, 0x6a, 0x4c, 0xd5, 0x98, 0xcc, 0xd5, 0xea, 0x46, 0xd0, 0xdf, 0xcb, 0xd4, 0x35, 0x4a,
	0x8f, 0xbc, 0xcb, 0x5b, 0xef, 0x41, 0xce, 0x21, 0x31, 0xac, 0xbe, 0xf7, 0xe2, 0x1f, 0xb9, 0xba,
	0x8f, 0xbd, 0x7b, 0x94, 0x9f, 0x7d, 0x00, 0x26, 0x4a, 0xf1, 0x1a, 0x8e, 0x5a, 0x31, 0x38, 0xca,
	0xf8, 0xb0, 0xd5, 0x43, 0xc9, 0xad, 0x3b, 0x74, 0xf6, 0x70, 0x28, 0xc1, 0x2b, 0x98, 0xde, 0xba,
	0xb7, 0xe0, 0x89, 0x13, 0x47, 0x9c, 0x87, 0xae, 0xdb, 0x47, 0xb2, 0xee, 0x50, 0xb8, 0x6d, 0x6f,
	0xab, 0x09, 0x8c, 0x0c, 0xd3, 0x5b, 0x34, 0xe9, 0x35, 0xcc, 0x63, 0xf8, 0x77, 0xfb, 0x19, 0x1e,
	0xe3, 0x07, 0xcc, 0x1b, 0x2b, 0x81, 0x4c, 0x2b, 0x11, 0xf5, 0x73, 0xd4, 0x5a, 0xa9, 0x12, 0x98,
	0xfe, 0xd5, 0xdb, 0x73, 0xa3, 0x1e, 0x9f, 0xed, 0xef, 0xf2, 0xd9, 0xfe, 0x9e, 0xa8, 0xfb, 0x13,
	0x3b, 0xbc, 0x84, 0xa4, 0xfd, 0xd8, 0x86, 0x2f, 0xc7, 0x69, 0x18, 0xde, 0x63, 0x85, 0xc5, 0x26,
	0x62, 0x74, 0xef, 0x46, 0xce, 0x60, 0x68, 0xfb, 0xf7, 0x4b, 0xfc, 0xf8, 0x53, 0xe7, 0x01, 0xf2,
	0x0a, 0xc6, 0x7e, 0x47, 0x71, 0x7f, 0x4f, 0xa4, 0x11, 0x51, 0x72, 0x0e, 0xb3, 0x92, 0x71, 0xd1,
	0x68, 0x3c, 0x5c, 0xdf, 0x61, 0xc4, 0x69, 0xc0, 0xdd, 0x2c, 0x47, 0x7f, 0xb8, 0xbf, 0xc4, 0xed,
	0xc8, 0x3d, 0x9f, 0xab, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x5f, 0xee, 0x73, 0x49, 0x06,
	0x00, 0x00,
}
