// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2019-08-22 17:13:37.783157053 -0700 PDT m=+5.000301635

package datacatalog

import (
	"fmt"

	"github.com/spf13/pflag"
)

// GetPFlagSet will return strongly types pflags for all fields in ClientConfig and its nested types. The format of the
// flags is json-name.json-sub-name... etc.
func (ClientConfig) GetPFlagSet(prefix string) *pflag.FlagSet {
	cmdFlags := pflag.NewFlagSet("ClientConfig", pflag.ExitOnError)
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "endpoint"), "", "Specify where the uri of the datacatalog service is located.")
	cmdFlags.Bool(fmt.Sprintf("%v%v", prefix, "insecure"), *new(bool), "Use insecure connection to the service.")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "maxBackoffDelay"), "", "Max delay for grpc backoff")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "perRetryTimeout"), "", "gRPC per retry timeout")
	cmdFlags.Int(fmt.Sprintf("%v%v", prefix, "maxRetries"), *new(int), "Max number of gRPC retries")
	return cmdFlags
}
