// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2019-01-08 17:21:43.013173 -0800 PST m=+6.923102353

package events

import (
	"fmt"

	"github.com/spf13/pflag"
)

// GetPFlagSet will return strongly types pflags for all fields in Config and its nested types. The format of the
// flags is json-name.json-sub-name... etc.
func (Config) GetPFlagSet(prefix string) *pflag.FlagSet {
	cmdFlags := pflag.NewFlagSet("Config", pflag.ExitOnError)
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "type"), *new(string), "Sets the type of EventSink to configure [log/admin/file].")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "file-path"), *new(string), "For file types,  specify where the file should be located.")
	return cmdFlags
}
