// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2018-10-08 15:32:08.218656382 -0700 PDT m=+4.368252638

package events

import (
	"fmt"

	"github.com/spf13/pflag"
)

// GetPFlagSet will return strongly types pflags for all fields in EventSinkConfig and its nested types. The format of the
// flags is json-name.json-sub-name... etc.
func (EventSinkConfig) GetPFlagSet(prefix string) *pflag.FlagSet {
	cmdFlags := pflag.NewFlagSet("EventSinkConfig", pflag.ExitOnError)
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "type"), *new(string), "Sets the type of EventSink to configure [log/admin/file].")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "file-path"), *new(string), "For file types,  specify where the file should be located.")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "endpoint"), "", "For admin types,  specify where the uri of the service is located.")
	return cmdFlags
}
