// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2018-10-08 15:32:08.218656382 -0700 PDT m=+4.368252638

package events

import (
	"encoding/json"
	"fmt"
	"reflect"
	"testing"

	"github.com/mitchellh/mapstructure"
	"github.com/stretchr/testify/assert"
)

var dereferencableKindsEventSinkConfig = map[reflect.Kind]struct{}{
	reflect.Array: {}, reflect.Chan: {}, reflect.Map: {}, reflect.Ptr: {}, reflect.Slice: {},
}

// Checks if t is a kind that can be dereferenced to get its underlying type.
func canGetElementEventSinkConfig(t reflect.Kind) bool {
	_, exists := dereferencableKindsEventSinkConfig[t]
	return exists
}

// This decoder hook tests types for json unmarshaling capability. If implemented, it uses json unmarshal to build the
// object. Otherwise, it'll just pass on the original data.
func jsonUnmarshalerHookEventSinkConfig(_, to reflect.Type, data interface{}) (interface{}, error) {
	unmarshalerType := reflect.TypeOf((*json.Unmarshaler)(nil)).Elem()
	if to.Implements(unmarshalerType) || reflect.PtrTo(to).Implements(unmarshalerType) ||
		(canGetElementEventSinkConfig(to.Kind()) && to.Elem().Implements(unmarshalerType)) {

		raw, err := json.Marshal(data)
		if err != nil {
			fmt.Printf("Failed to marshal Data: %v. Error: %v. Skipping jsonUnmarshalHook", data, err)
			return data, nil
		}

		res := reflect.New(to).Interface()
		err = json.Unmarshal(raw, &res)
		if err != nil {
			fmt.Printf("Failed to umarshal Data: %v. Error: %v. Skipping jsonUnmarshalHook", data, err)
			return data, nil
		}

		return res, nil
	}

	return data, nil
}

func decode_EventSinkConfig(input, result interface{}) error {
	config := &mapstructure.DecoderConfig{
		TagName:          "json",
		WeaklyTypedInput: true,
		Result:           result,
		DecodeHook: mapstructure.ComposeDecodeHookFunc(
			mapstructure.StringToTimeDurationHookFunc(),
			mapstructure.StringToSliceHookFunc(","),
			jsonUnmarshalerHookEventSinkConfig,
		),
	}

	decoder, err := mapstructure.NewDecoder(config)
	if err != nil {
		return err
	}

	return decoder.Decode(input)
}

func testDecodeJson_EventSinkConfig(t *testing.T, val, result interface{}) {
	assert.NoError(t, decode_EventSinkConfig(val, result))
}

func testDecodeSlice_EventSinkConfig(t *testing.T, vStringSlice, result interface{}) {
	assert.NoError(t, decode_EventSinkConfig(vStringSlice, result))
}

func TestEventSinkConfig_GetPFlagSet(t *testing.T) {
	val := EventSinkConfig{}
	cmdFlags := val.GetPFlagSet("")
	assert.True(t, cmdFlags.HasFlags())
}

func TestEventSinkConfig_SetFlags(t *testing.T) {
	actual := EventSinkConfig{}
	cmdFlags := actual.GetPFlagSet("")
	assert.True(t, cmdFlags.HasFlags())

	t.Run("Test_type", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("type"); err == nil {
				assert.Equal(t, *new(string), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			cmdFlags.Set("type", "1")
			if vString, err := cmdFlags.GetString("type"); err == nil {
				testDecodeJson_EventSinkConfig(t, fmt.Sprintf("%v", vString), &actual.Type)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_file-path", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("file-path"); err == nil {
				assert.Equal(t, *new(string), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			cmdFlags.Set("file-path", "1")
			if vString, err := cmdFlags.GetString("file-path"); err == nil {
				testDecodeJson_EventSinkConfig(t, fmt.Sprintf("%v", vString), &actual.FilePath)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_endpoint", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("endpoint"); err == nil {
				assert.Equal(t, "", vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			cmdFlags.Set("endpoint", "1")
			if vString, err := cmdFlags.GetString("endpoint"); err == nil {
				testDecodeJson_EventSinkConfig(t, fmt.Sprintf("%v", vString), &actual.Endpoint)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
}
